### ISSUE TITLE
Make a new 3.0 release

### ISSUE THREAD

**Issue by romm** [thecodingmachine/service-provider-registry#6]
The package `thecodingmachine/service-provider-bridge-bundle` requires `thecodingmachine/service-provider-registry:^3.0` (see [composer.json definition](https://github.com/thecodingmachine/service-provider-bridge-bundle/blob/7ac2d64c6aa7f093ad36fb1f3a4b86b397777c99/composer.json#L17)), but no tag `3.x` was created for this package. Possible to make a new release?

**Comment by moufmouf** [comment]
Tagged! Thanks for the PRs and the code review!
